# convert_cookies.py

import json

def json_to_cookies_txt(json_path, txt_path):
    with open(json_path, 'r') as json_file:
        cookies = json.load(json_file)
    
    with open(txt_path, 'w') as txt_file:
        # Write header for Netscape format
        txt_file.write("# Netscape HTTP Cookie File\n")
        txt_file.write("# https://curl.se/docs/http-cookies.html\n")
        txt_file.write("# This file was generated by yt-dlp\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure') else 'FALSE'
            expiration = str(int(cookie.get('expiry', 0)))  # Must be integer
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            txt_file.write(line)

    print(f"Cookies converted and saved to {txt_path}")

if __name__ == "__main__":
    json_to_cookies_txt("cookies.json", "cookies.txt")
