version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./config.ini:/app/config.ini
      - ./app.log:/app/app.log  # Ensure this is a file, not a directory
      - ./exported_cookies/cookies.txt:/app/cookies.txt  # Mount cookies.txt into /app/

    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=pose_db
      - YTDLP_COOKIES_PATH=/app/cookies.txt  # Environment variable for cookies path
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pose_db"]
      interval: 10s
      timeout: 5s
      retries: 5
